### ISSUE TITLE
Console reporter

### ISSUE THREAD

**Issue by resah** [bmuschko/gradle-clover-plugin#117]
Is it possible to write code coverage information to console?

We are using GitLab-CI, which reads coverage information from console output during build and shows this directly in related merge requests.

Right now I am using jacoco and would love to switch to this awesome clover plugin.

**Comment by Alex-Vol-SV** [comment]
If you enable XML report you can probably create a new task that uses XMLSlurper to pick the values out of the XML report and print them. Instead of just running the cloverGenerateReport or cloverAggregateReports task you would run your own task which would depend on either of the above as needed and then would pick the values out of the clover.xml summary. You would do that to print the desired values as part of the task action.

I could add that feature in the clover tasks either as what I just described or some more internalized functionality that possibly works even with XML report disabled. Although, I am not sure there is a proper API to get the necessary information from clover without enabling the report to use XML.

**Comment by keithh63** [comment]
plus 1. I would like to be able to show the coverage percentage in the build console output without having to open the report.

**Comment by Alex-Vol-SV** [comment]
Added console reporter feature when XML reports are used. The feature is activated automatically when the XML report is generated.

See update in README
