### ISSUE TITLE
unexpected token: enum on JDK10

### ISSUE THREAD

**Issue by taylorsmithgg** [bmuschko/gradle-clover-plugin#138]
#119 Says this was fixed, but I am still experiencing an issue.

Using
```
    dependencies {
        clover 'org.openclover:clover:4.3.1'
    }
```

and

```
classpath "com.bmuschko:gradle-clover-plugin:2.2.3"
```

**Comment by Alex-Vol-SV** [comment]
What version of OpenClover are you using? This is not an issue I can fix. Relies on changes from OpenClover.

**Comment by Alex-Vol-SV** [comment]
This is caused by OpenClover version selection.
4.3.0 or later I believe makes it work.

**Comment by Alex-Vol-SV** [comment]
By the way, if you want me to take any different action prove that it is this plugin that failed and not OpenClover with a reproducer and a stack trace. I do not have enough time to research this when all indications are this failed during the instrumentation step inside OpenClover code.

**Comment by taylorsmithgg** [comment]
I'll get you a sample.

**Comment by Alex-Vol-SV** [comment]
OpenClover does not support Java version 10 or later yet. I Added a new feature in the plugin to allow dropping down to Java 9 for the Clover compilation only. This solves the problem because in the original code the OpenClover library will auto-select the minimum Java version when the choice is not a supported Java version. As a result selecting Java 10 make Clover use Java 1.3 level which does not have `enum` as a keyword.

```
sourceCompatbility = '10'
targetCompatibility = '10'

clover {
   compiler {
       sourceCompatbility = '1.9'
       targetCompatibility = '1.9'
   }
}
```
