### ISSUE TITLE
Make compilerArgs configurable

### ISSUE THREAD

**Issue by prestontim** [bmuschko/gradle-clover-plugin#98]
I received a report from a developer in my company that's encountering an issue while attempting to write some unit tests for a Spring Boot app. The test in question is attempting to exercise some code that's utilizing the @PreAuthorize annotation and is getting the following message:

`Unable to resolve method parameter names for method: public java.lang.String com.example.api.TestApi.get(java.lang.Long). Debug symbol information is required if you are using parameter names in expressions.`

However, even with debug enabled in Clover, it's not sufficient for the test to pass. It's only when I explicitly added the "-parameters" compiler argument, that I could get the test to pass with Clover.
![compilerargs](https://user-images.githubusercontent.com/8949320/29564570-fae00f98-8707-11e7-9e91-f9d60d2ada78.png)

Sample app contains a test that will pass when the Clover-related lines are commented out and will fail when Clover is applied/configured. [sample.zip](https://github.com/bmuschko/gradle-clover-plugin/files/1241923/sample.zip)

**Comment by Alex-Vol** [comment]
Thank you for the report and the sample app. I will take a look at this soon. Since you already have a possible solution I can look into extending the DSL to have a `compilerArgs` option that can contain the raw additional arguments that make this work. Seems that there are more nuances to the reflection based application frameworks that must be cared for.
